# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.TextField(max_length=30),
        ),
    ]
