# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170704_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.TextField(max_length=31),
        ),
    ]
