# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_code',
        ),
        migrations.AddField(
            model_name='productcategories',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_code',
            field=models.ManyToManyField(related_name='product_categories', through='product.ProductCategories', to='product.Category'),
        ),
    ]
