# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 12:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}, null=True),
        ),
    ]
