# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='price_list_code',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='code',
            field=models.CharField(default='0011ff', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
