# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170711_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_code',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='max_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='recorded_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
