# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170803_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_override',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_override_currency',
        ),
    ]
