# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170708_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceListDetials',
            new_name='PriceListDetial',
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='description',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
