# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170706_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('price_list_code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validate_till', models.DateField()),
                ('blocked_till', models.DateField()),
                ('status', models.CharField(choices=[('WIP', 'Payment in advance'), ('EOM', 'End of the month'), ('CWO', 'Cash with order')], default='WIP', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PriceListDetials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unit', models.TextField(max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_list_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.PriceList')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.TextField(default='11ddre', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 8, 10, 37, 5, 288930, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='011', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='recorded_stock_level',
            field=models.DecimalField(decimal_places=2, default='23', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='pricelistdetials',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
