# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170711_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(through='product.ProductCategories', to='product.Category'),
        ),
    ]
