# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 14:20
from __future__ import unicode_literals

from django.db import migrations
import product.managers


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170804_1339'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', product.managers.ProductManager()),
            ],
        ),
    ]
