# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170709_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
