# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user_id', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('code', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30, unique=True)),
                ('location', models.TextField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user_id', models.TextField(max_length=15)),
                ('warehouse_keeper_id', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
                ('warehouse_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='category_code',
            field=models.ManyToManyField(through='inventory.WarehouseCategory', to='inventory.Category'),
        ),
    ]
