# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('customer', models.CharField(max_length=40)),
                ('order_number', models.IntegerField()),
            ],
        ),
    ]
