# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_order_items',
            field=models.ManyToManyField(through='sales.SalesOrderDetails', to='product.Product'),
        ),
    ]
