# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170708_1217'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='price_list_code',
            field=models.ForeignKey(default='2342fdg', on_delete=django.db.models.deletion.CASCADE, to='product.PriceList'),
            preserve_default=False,
        ),
    ]
