# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='price_list_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='product.PriceList'),
        ),
    ]
