# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
