# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170706_0433'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unit', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('ordered_qty', models.IntegerField()),
                ('delivered_qty', models.IntegerField()),
                ('note', models.TextField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.SalesOrder')),
            ],
        ),
        migrations.RemoveField(
            model_name='salesorderdetails',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='salesorderdetails',
            name='sales_order_id',
        ),
        migrations.DeleteModel(
            name='SalesOrderDetails',
        ),
    ]
