# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer_order_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sale_order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='delivered_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='ordered_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
