# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170706_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderdetail',
            old_name='sales_order_id',
            new_name='order_id',
        ),
    ]
