# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170711_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='note',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
