# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170708_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='price_list_code',
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_term',
            field=models.CharField(choices=[('PIA', 'Payment in advance'), ('EOM', 'End of the month'), ('CWO', 'Cash with order')], default='EOM', max_length=5),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('WIP', 'working in process'), ('INVOICED', 'invoiced')], default='WIP', max_length=5),
        ),
    ]
