# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20170708_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='note',
            field=models.TextField(max_length=50),
        ),
    ]
