# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20170709_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='product_unit',
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='note',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.SalesOrder'),
        ),
    ]
