# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20170709_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderdetail',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
